# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - hagglemarketplace

on:
  push:
    branches:
      - dev
  workflow_dispatch:

defaults:
  run:
    working-directory: expressjs-backend

jobs:
  build:
    runs-on: windows-latest

    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET }}

      - name: Zip artifact for deployment
        run: Compress-Archive -Path * -DestinationPath backend.zip
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: expressjs-backend/backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: list files
        run: ls -lR

      - name: unzip artifact for dployment
        run: Expand-Archive -Path backend.zip -DestinationPath .
        working-directory: .

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'hagglemarketplace'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B5649FCE631E4A69AACB1628EF2A7D8C }}
          package: .
